### ISSUE TITLE
Multiple paths

### ISSUE THREAD

**Issue by diegohaz** [Rowno/react-benchmark#2]
Awesome project, @Rowno. Thank you so much. 

I'm trying to use it to do some benchmarks for https://github.com/diegohaz/reas. I'd like to compare it with other libs. So I'll `npm install` them, create one file per lib and run `react-benchmark` on each of them.

Is that what you recommend for testing multiple paths? It would be nice being able to pass multiple paths to `react-benchmark` in order to compare them. Just a suggestion.

**Comment by Rowno** [comment]
Yeah, I'd recommend doing a separate run for each of them. It's probably a good idea to run them separately anyway so they aren't fighting for the CPU.

**Comment by diegohaz** [comment]
Alright, thank you. Would you mind to publish a new release? 

I'm particularly interested in this commit: d55ef3926915bcf56dd071380e6e515dda7387a0

EDIT: Nevermind, I figured out another way to do that.

**Comment by Rowno** [comment]
I finally got around to finishing up and releasing the new [programmatic API](https://github.com/Rowno/react-benchmark#api), which you might find useful.

**Comment by diegohaz** [comment]
Cool. I'll try that. Thank you, @Rowno.
